# Generated by Django 4.2.2 on 2023-06-26 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_remove_petmatch_matchstatus_remove_pettable_prompt1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pettable',
            name='prompt1',
        ),
    ]
